name: multihmr
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pip
  - pip:
    - roma
    - pillow==10.0.1
    - pyrender==0.1.45
    - einops==0.6.1
    - smplx
    - pyvista==0.42.3
    - numpy==1.22.4
    - xformers==0.0.20
    - tqdm==4.65.0
    - trimesh==3.22.3
    - pyglet==1.5.24
    - gradio==4.13.0
    - scikit-learn==1.6.1
    - filterpy==1.4.5
    - chumpy==0.70




